# Generated by Django 5.2.15 on 2026-07-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
