# Generated by Django 5.2.15 on 2026-07-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgeraccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
