# Generated by Django 5.2.15 on 2026-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_ledgeraccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(choices=[('external_funding', 'External Funding'), ('wallet', 'UserWallet'), ('withdrawal_pending', 'Withdrawal Pending')], max_length=20),
        ),
    ]
