# Generated by Django 5.2.15 on 2026-07-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='wallets.wallet')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_details', to='transactions.transaction')),
            ],
        ),
    ]
