# Generated by Django 5.2.15 on 2026-07-22 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_idempotencyrecord_unique_idempotency_key_per_user_operation'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_withdrawals', to='wallets.wallet')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_details', to='transactions.transaction')),
            ],
        ),
    ]
