# Generated by Django 5.2.15 on 2026-07-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='receiver_wallet',
        ),
    ]
